language: go

go:
  - master

os:
  - linux

services:
  - docker

before_install:
  - docker-compose -f test/docker-compose.yml up -d
  - docker ps -a

script: go test -v ./...

after_script:
  rm logs/*
