language: go

stages:
  - test
  - ship

jobs:
  include:
    - stage: test
      os: linux
      go: master
      env: TARGET=kafka-test
    - os: linux
      go: master
      env: TARGET=go-test
      after_script:
        - bash <(curl -s https://codecov.io/bash)
    - stage: ship
      os: linux
      go: master
      env: TARGET=docker-push-local
      script: make docker-push-local docker-version=latest
      before_script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin 

addons:
  hosts:
    - kafka

services:
  - docker

script: make $TARGET
