language: go

jobs:
  include:
    - os: linux
      go: master
      env: TARGET=kafka-test
    - os: linux
      go: master
      env: TARGET=go-test

addons:
  hosts:
    - kafka

services:
  - docker

before_install:
  - docker-compose -f test/docker-compose.yml up -d
  - docker ps -a

script: make $TARGET

after_script:
  rm logs/* || true

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin 
  - docker build --tag log-formatter .
  - docker tag log-formatter vertexc/log-formatter
  - docker push vertexc/log-formatter:latest
