language: go

jobs:
  include:
    - os: linux
      go: master
      env: TARGET=kafka-consumer-test
    - os: linux
      go: master
      env: TARGET=go-test

addons:
  hosts:
    - kafka

services:
  - docker

before_install:
  - docker-compose -f test/docker-compose.yml up -d
  - docker ps -a

script: make $TARGET

after_script:
  rm logs/* || true
