// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package controller

import (
	context "context"
	agent "github.com/VertexC/log-formatter/proto/pkg/agent"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// ControllerClient is the client API for Controller service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ControllerClient interface {
	UpdateAgentStatusRequest(ctx context.Context, in *agent.HeartBeat, opts ...grpc.CallOption) (*ControllerRequestDone, error)
}

type controllerClient struct {
	cc grpc.ClientConnInterface
}

func NewControllerClient(cc grpc.ClientConnInterface) ControllerClient {
	return &controllerClient{cc}
}

func (c *controllerClient) UpdateAgentStatusRequest(ctx context.Context, in *agent.HeartBeat, opts ...grpc.CallOption) (*ControllerRequestDone, error) {
	out := new(ControllerRequestDone)
	err := c.cc.Invoke(ctx, "/controllerpb.Controller/UpdateAgentStatusRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ControllerServer is the server API for Controller service.
// All implementations must embed UnimplementedControllerServer
// for forward compatibility
type ControllerServer interface {
	UpdateAgentStatusRequest(context.Context, *agent.HeartBeat) (*ControllerRequestDone, error)
	mustEmbedUnimplementedControllerServer()
}

// UnimplementedControllerServer must be embedded to have forward compatible implementations.
type UnimplementedControllerServer struct {
}

func (UnimplementedControllerServer) UpdateAgentStatusRequest(context.Context, *agent.HeartBeat) (*ControllerRequestDone, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAgentStatusRequest not implemented")
}
func (UnimplementedControllerServer) mustEmbedUnimplementedControllerServer() {}

// UnsafeControllerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ControllerServer will
// result in compilation errors.
type UnsafeControllerServer interface {
	mustEmbedUnimplementedControllerServer()
}

func RegisterControllerServer(s grpc.ServiceRegistrar, srv ControllerServer) {
	s.RegisterService(&_Controller_serviceDesc, srv)
}

func _Controller_UpdateAgentStatusRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(agent.HeartBeat)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).UpdateAgentStatusRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controllerpb.Controller/UpdateAgentStatusRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).UpdateAgentStatusRequest(ctx, req.(*agent.HeartBeat))
	}
	return interceptor(ctx, in, info, handler)
}

var _Controller_serviceDesc = grpc.ServiceDesc{
	ServiceName: "controllerpb.Controller",
	HandlerType: (*ControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateAgentStatusRequest",
			Handler:    _Controller_UpdateAgentStatusRequest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "controller/controller.proto",
}
